pipline: runwayml/stable-diffusion-v1-5
vae_save_path: runwayml/stable-vae-v1-5
device: cpu
clip_save_path: clip
clip_processor_save_path: clip_processor
model_save_path: models/model_save
image_save_path: assets
image_channels: 3
output_channels: 3
res_layers: 2
train_image_size: 512
dataset_path: models/clothdataset
injected_dataset_path: models/injected_dataset
train_timesteps: 1000
batch_size: 1
epochs : 1
lr: 5e-6
use_text_attention: True
model_input_channels: 4
model_input_size: 64
model_output_path: output
sequence_length: 77
log_path: models/log
inner_train_step: 1
target_image_path: Target2.png
delta_save_path: models/delta
text_encoder_train_step: 400
text_encoder_epochs: 1


